name: tech-blog
description: 태용's 기술 블로그
meta_description: 프론트엔드 기술블로그

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /tech-blog
domain_name: "https://bpthess.github.io/tech-blog"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://bpthess.github.io/tech-blog"
author: "tyLee"

# Disqus config
disqus-shortname: ""
